## NETWORK SETTINGS ##
subnet: 192.168.1.*                   # Subnet to search in for SmartDevices
deviceTimeout: 500                    # Timeout for SmartDevice ping
######################

## LOGGING SETTINGS ##
showDebugMessages: true               # Enables/Disables debug messages in the log. Turn this on if you encounter an error!
showDeviceIndexerDebugMessages: true  # Enables/Disables debug messages for the DeviceIndexer. This might be a little spammy...
######################

#### WEB SETTINGS ####
httpServerPort: 80                    # Exactly what you think it is
masterKey: "uielaidhesldidef"         # 16 chars long security key for the REST API
######################